[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[identity]
  confirmation_url = "https://georgeangulofitness.netlify.app/confirm"
  invitation_url = "https://georgeangulofitness.netlify.app/invite"
  password_reset_url = "https://georgeangulofitness.netlify.app/reset-password"
